[32m2024-10-01 11:16:57 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 7064c91f-ea73-4603-aa7a-78a7cd0ae786 - 2079102 - LOGS_CAPTURED - Started capturing logs in process (pid: 2079102).
[32m2024-10-01 11:16:57 -0400[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 7064c91f-ea73-4603-aa7a-78a7cd0ae786 - 2079102 - dbt_project_assets - STEP_START - Started execution of step "dbt_project_assets".
[32m2024-10-01 11:16:57 -0400[0m - dagster - [34mINFO[0m - __ASSET_JOB - 7064c91f-ea73-4603-aa7a-78a7cd0ae786 - dbt_project_assets - A dbt subsetted execution is being performed. Overriding default dbt selection arguments `['--select', 'fqn:*']` with arguments: `['nfl.flex_stats']`.
[32m2024-10-01 11:16:58 -0400[0m - dagster - [34mINFO[0m - __ASSET_JOB - 7064c91f-ea73-4603-aa7a-78a7cd0ae786 - dbt_project_assets - Copying `/home/christianocean/mta/nfl/transformations/dbt/target/partial_parse.msgpack` to `/home/christianocean/mta/nfl/transformations/dbt/target/dbt_project_assets-7064c91-a988bc2/partial_parse.msgpack` to take advantage of partial parsing.
[32m2024-10-01 11:16:58 -0400[0m - dagster - [34mINFO[0m - __ASSET_JOB - 7064c91f-ea73-4603-aa7a-78a7cd0ae786 - dbt_project_assets - Running dbt command: `dbt build --select nfl.flex_stats`.
[32m2024-10-01 11:16:59 -0400[0m - dagster - [34mINFO[0m - __ASSET_JOB - 7064c91f-ea73-4603-aa7a-78a7cd0ae786 - dbt_project_assets - Finished dbt command: `dbt build --select nfl.flex_stats`.
[32m2024-10-01 11:16:59 -0400[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 7064c91f-ea73-4603-aa7a-78a7cd0ae786 - 2079102 - dbt_project_assets - STEP_FAILURE - Execution of step "dbt_project_assets" failed.

dagster_dbt.errors.DagsterDbtCliRuntimeError: The dbt CLI process with command

`dbt build --select nfl.flex_stats`

failed with exit code `1`. Check the stdout in the Dagster compute logs for the full information about the error, or view the dbt debug log: /home/christianocean/mta/nfl/transformations/dbt/target/dbt_project_assets-7064c91-a988bc2/dbt.log.

Errors parsed from dbt logs:

1 of 1 ERROR creating sql table model main.flex_stats .......................... [[31mERROR[0m in 0.12s]

  Runtime Error in model flex_stats (models/flex_stats.sql)
  Catalog Error: Table with name pbp does not exist!
  Did you mean "pg_am"?
  LINE 25:     FROM pbp
                    ^

Stack Trace:
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_plan.py", line 247, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 500, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 184, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/execute_step.py", line 88, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 198, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster/_core/execution/plan/compute.py", line 167, in _yield_compute_results
    for event in iterate_with_context(
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster/_utils/__init__.py", line 478, in iterate_with_context
    next_output = next(iterator)
  File "/home/christianocean/mta/nfl/assets/dbt.py", line 7, in dbt_project_assets
    yield from dbt.cli(["build"], context=context).stream()
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster_dbt/core/dbt_event_iterator.py", line 203, in __next__
    return next(self._inner_iterator)
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 269, in _stream_asset_events
    for event in self.stream_raw_events():
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 362, in stream_raw_events
    self._raise_on_error()
  File "/home/christianocean/mta/.venv/lib/python3.10/site-packages/dagster_dbt/core/dbt_cli_invocation.py", line 454, in _raise_on_error
    raise error
[0m
